export const countries = [
  "Argentina",
  "Bahamas",
  "Barbados",
  "Belize",
  "Bolivia",
  "Brazil",
  "Canada",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Grenada",
  "Guatemala",
  "Guyana",
  "Haiti",
  "Honduras",
  "Jamaica",
  "Mexico",
  "Nicaragua",
  "Panama",
  "Paraguay",
  "Peru",
  "United States",
  "Uruguay",
  "Venezuela",
];

export const services = [
  "Host",
  "Flight",
  "Accommodation",
  "Transportation",
  "Restaurant / Food",
  "Tour",
  "Photography and Video",
  "Entertainment",
  "Wellness and Spa",
  "Insurance and Assistance",
  "Technology and Comunication",
  "Logistics",
  "Others",
];

export const testVendor = {
  id: "5",
  name: "Vendor Test - Edit created Vendor",
  location: "Colombia",
  services: "Transportation, Restaurant / Food",
  email: "testEmail@k2con.com",
  createdAt: "09/04/2025",
  status: "Active",
  phone: "+573137985652",
  website: "https://cumbersome-petticoat.name",
};

export const testTripUser = {
  Id: "8",
  name: "Lisseth Moreno",
  email: "lisshahimor_09@hotmail.com",
  identification: "AD939498",
  address: "cra 23 122 89 Bogota, 110111",
  country: "Colombia",
  phone: "+573168293576",
  BirthDate: "11/05/1992",
}
