name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Allure CLI
      run: npm i -D allure-commandline

    - name: Run Playwright tests
      run: npx playwright test --reporter=allure-playwright

    - name: Generate Allure Report
      run: npx allure-commandline generate allure-results --clean -o allure-report

    - name: Upload Allure Results (Raw Data)
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30

    - name: Upload Allure Report (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Allure Report
      uses: actions/download-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GH_PAT }}
        branch: gh-pages
        folder: allure-report

